package com.amrshalaby.timesheet.audit;

public enum AuditEventType {
    USER_CREATED,
    USER_UPDATED,
    USER_DISABLED,
    USER_REACTIVATED,
    USER_ROLE_CHANGED,
    USER_MANAGER_CHANGED,
    PASSWORD_RESET,
    TIMESHEET_CREATED,
    TIMESHEET_SUBMITTED,
    TIMESHEET_APPROVED,
    TIMESHEET_REOPENED,
    TIMESHEET_PRIVILEGED_EDITED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED
}
