package com.amrshalaby.timesheet.timesheet;
import com.amrshalaby.timesheet.audit.AuditService; import com.amrshalaby.timesheet.user.UserRole; import jakarta.inject.Singleton; import jakarta.transaction.Transactional; import java.time.*; import java.util.*;
@Singleton public class TimesheetService { private final MonthlyTimesheetRepository sheets; private final DailyTimeEntryRepository entries; private final AuditService audit; public TimesheetService(MonthlyTimesheetRepository sheets, DailyTimeEntryRepository entries, AuditService audit){this.sheets=sheets;this.entries=entries;this.audit=audit;}
 @Transactional public MonthlyTimesheet getOrCreate(Long userId,int year,int month){return sheets.findByUserIdAndYearAndMonth(userId,year,month).orElseGet(()->{MonthlyTimesheet t=new MonthlyTimesheet(); t.setUserId(userId); t.setYear(year); t.setMonth(month); t.setStatus(TimesheetStatus.DRAFT); return sheets.save(t);});}
 public List<DailyTimeEntry> entries(Long sheetId){return entries.findByTimesheetId(sheetId);} 
 @Transactional public void submit(Long actor, MonthlyTimesheet t, UserRole role, boolean scoped){ if(!StatusTransitionPolicy.canSubmit(t.getStatus(),role,scoped)) throw new SecurityException("Cannot submit timesheet"); t.setStatus(TimesheetStatus.SUBMITTED); t.setSubmittedAt(Instant.now()); t.setSubmittedByUserId(actor); sheets.update(t); audit.record(actor,t.getUserId(),"TIMESHEET_SUBMITTED","monthly_timesheet",t.getId(),"{}"); }
 @Transactional public void approve(Long actor, MonthlyTimesheet t, UserRole role, boolean scoped){ if(!StatusTransitionPolicy.canApprove(t.getStatus(),role,scoped)) throw new SecurityException("Cannot approve timesheet"); t.setStatus(TimesheetStatus.APPROVED); t.setApprovedAt(Instant.now()); t.setApprovedByUserId(actor); sheets.update(t); audit.record(actor,t.getUserId(),"TIMESHEET_APPROVED","monthly_timesheet",t.getId(),"{}"); }
 @Transactional public void reopen(Long actor, MonthlyTimesheet t, UserRole role, boolean scoped, String reason){ if(reason==null||reason.isBlank()) throw new IllegalArgumentException("Reopening reason is required."); if(!StatusTransitionPolicy.canReopen(t.getStatus(),role,scoped)) throw new SecurityException("Cannot reopen timesheet"); TimesheetStatus before=t.getStatus(); t.setStatus(TimesheetStatus.DRAFT); t.setSubmittedAt(null); t.setSubmittedByUserId(null); t.setApprovedAt(null); t.setApprovedByUserId(null); sheets.update(t); audit.record(actor,t.getUserId(),"TIMESHEET_REOPENED","monthly_timesheet",t.getId(),"{\"previous_status\":\""+before+"\",\"new_status\":\"DRAFT\",\"reason\":\""+reason.replace("\"","'")+"\"}"); }
}
